Feature basic
cacachang/5xruby_url pull request #1
Opened 2022-10-06 17:33 UTC by cacachang

短網址
1. 新增網址
2. 建立 utm 參數
3. 產生短網址
4. 重新導向原網址
5. 會員註冊 / 登入 / 登出功能

2022-10-06 17:44 UTC, cacachang commented
@kaochenlong
@Robeeerto

2022-10-06 23:33 UTC, kaochenlong requested changes

2022-10-06 23:33 UTC, kaochenlong commented on app/controllers/home_controller.rb
> +    @env = ENV['DOMAIN']
可考慮使用 `ENV.fetch('DOMAIN', 'localhost:3000')`，萬一沒設定也可以有預設值

2022-10-06 23:33 UTC, kaochenlong commented on app/controllers/application_controller.rb
> +  protected
可改用 `private`

2022-10-06 23:33 UTC, kaochenlong commented on app/controllers/application_controller.rb
> +  def configure_permitted_parameters
可移去 devise 的專屬 controller

2022-10-06 23:33 UTC, kaochenlong commented on app/controllers/urls_controller.rb
> +  require 'uri'
這應該可省略，Rails 本來就有 require 它了

2022-10-06 23:33 UTC, kaochenlong commented on app/controllers/urls_controller.rb
> +    redirect_to @url.utm_url, allow_other_host: true
`allow_other_host` 的預設值本來就是 `true`，可省略

2022-10-06 23:33 UTC, kaochenlong commented on app/controllers/urls_controller.rb
> +    if @url.save || @campaign.save
就只是把資料抓出來，`save` 了什麼？

2022-10-06 23:33 UTC, kaochenlong commented on app/views/layouts/application.html.erb
> +    <% if user_signed_in? %>
把這段整理成一個 partial render

2022-10-06 23:33 UTC, kaochenlong commented on db/migrate/20221006074535_add_utm_url_to_url.rb
> +    add_column :urls, :utm_url, :text
應該不需要用到 `text` 這麼大的欄位

2022-10-06 23:33 UTC, kaochenlong commented on app/models/url.rb
> +  require 'securerandom'
這個不需要 require

2022-10-07 01:55 UTC, heyrobertchang commented on .env.example
> +DOMAIN=http://localhost:3000
有用使用環境變數的習慣很讚！

2022-10-07 01:55 UTC, Robeeerto commented on app/controllers/urls_controller.rb
> +      render :new
若是使用 `Rails 7`，通常在在 `save` 失敗的時候，會加上 `status: :unprocessable_entity`

可以去研究一下，不加這個會發生什麼事唷！

2022-10-07 01:55 UTC, heyrobertchang commented on app/controllers/urls_controller.rb
> +  end
在 Rails 大部分都認同的 Coding Style 中，沒有做事情的 action 通常都會寫成：
```ruby
def edit; end
```

2022-10-07 14:57 UTC, cacachang commented on app/controllers/urls_controller.rb
> +    if @url.save || @campaign.save
要使用 update ，我再來做調整

2022-10-08 09:00 UTC, cacachang commented on app/controllers/urls_controller.rb
> +      render :new
好！ save 失敗的時候， HTTP 狀態依然是 200 ，這時 Turbo 只會停在原本的畫面，不會去執行對應的方法
要給他設定狀態是 422 Unprocessable Entity 後， Turbo 才會知道要 render 錯誤訊息

2022-10-10 14:04 UTC, merged